sudo: required
services:
  - docker

before_install:
  - docker build -t chase/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chase/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-905418291268"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY$
  secret_access_key: $AWS_SECRET_KEY$